### ISSUE TITLE
npm install  error, cannot find module @compodoc\compodoc\tools\copy-libs.js

### ISSUE THREAD

**Issue by toneyyq** [shopizer-ecommerce/shopizer-admin#92]
> @compodoc/compodoc@1.1.25 copy-libs
> node tools/copy-libs.js

internal/modules/cjs/loader.js:818nfig:load:flatten Completed in 2ms
  throw err;
  ^

Error: Cannot find module '**\shopizer-admin\node_modules\@compodoc\compodoc\tools\copy-libs.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

QTA: package.json  @compodoc/compodoc version is 1.1.15, but use 1.1.25 in npm install, and I again rm node_modules and package_local.json, but it didn't work .
and I not find tools  dir in npm

**Comment by toneyyq** [comment]
@compodoc  v 1.1.15 and  v 1.1.25   all not find tools dir

**Comment by toneyyq** [comment]
need update package.json       "angular-file": "^3.1.2",     to   "angular-file": "3.1.2",
